#!/usr/bin/env perl
use strict;
use warnings;
use lib 'lib';
use FindBin;

our $LOCAL = $FindBin::Bin;
our @ARGV;

warn "korapxml2krill_dir is DEPRECATED. Please use korapxml2krill";
system("perl $LOCAL/korapxml2krill archive " . join(' ', @ARGV));

__END__
